;Custom_OpenClash_Rules
;全分组防DNS泄漏订阅转换模板
;作者：https://github.com/Aethersailor
;基于 ACL4SSR 模板魔改而来
;项目地址：https://github.com/Aethersailor/Custom_OpenClash_Rules
;强烈建议搭配本项目配套教程，实现最佳化的 OpenClash 使用效果！
;教程：https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%A1%88
;有问题可提 issue，或者加入本项目 Telegram 群组进行讨论
;Telegram 群组：https://t.me/custom_openclash_rules_group
;Telegram 通知频道：https://t.me/custom_openclash_rules

[custom]
;设置规则标志位
;以下规则，按照从上往下的顺序遍历，优先命中上位规则
;修改顺序会影响分流效果

ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Direct.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Steam_CDN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list
ruleset=🎶 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🕊️ Twitter(X),https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list
ruleset=💬 ChatGPT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=💬 Copilot,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list
ruleset=🤖 AI,https://raw.githubusercontent.com/maelitoandres/Custom_OpenClash_Rules/refs/heads/main/rule/usa.list
ruleset=🚀 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=🪙 加密货币,https://raw.githubusercontent.com/maelitoandres/Custom_OpenClash_Rules/refs/heads/main/rule/Coin.list
ruleset=🚀 测速工具,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=🇬 谷歌服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=🍘️ 小米服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XiaoMi/XiaoMi.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🎥 DisneyPlus,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🎥 HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.list
ruleset=🎥 PrimeVideo,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.list
ruleset=🎥 Emby,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.list
ruleset=🎥 Emby,https://raw.githubusercontent.com/ddgksf2013/Filter/refs/heads/master/Emby.list
ruleset=🎻 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=📺 Bahamut,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
ruleset=🎶 网易音乐,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.list
ruleset=📺 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🌎 国外媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
ruleset=🛒 国外电商,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Amazon/Amazon.list
ruleset=🛒 国外电商,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AmazonIP/AmazonIP.list
ruleset=🛒 国外电商,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Shopee/Shopee.list
ruleset=🛒 国外电商,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Shopify/Shopify.list
ruleset=🛒 国外电商,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/Ozon.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=📕 小红书,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/XiaoHongShu/XiaoHongShu.list
ruleset=🎶 抖音,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/DouYin/DouYin.list,https://raw.githubusercontent.com/maelitoandres/Custom_OpenClash_Rules/refs/heads/main/rule/colombia.list
ruleset=📕 微博,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Loon/Weibo/Weibo.list
ruleset=📺 国内媒体,https://raw.githubusercontent.com/maelitoandres/Custom_OpenClash_Rules/refs/heads/main/rule/trabajo.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list
ruleset=🎯 全球直连,[]GEOSITE,category-public-tracker
ruleset=🎯 全球直连,[]GEOIP,LAN,no-resolve
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位结束

;设置节点分组标志位
custom_proxy_group=🎶 TikTok`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🚀 GitHub`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🎶 抖音`select`[]DIRECT`[]美国-自动`[]哥伦比亚-家里`[]哥伦比亚-公司`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=📕 小红书`select`[]DIRECT`[]美国-自动`[]哥伦比亚-家里`[]哥伦比亚-公司`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=📕 微博`select`[]DIRECT`[]美国-自动`[]哥伦比亚-家里`[]哥伦比亚-公司`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=📲 Telegram`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🕊️ Twitter(X)`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=💬 ChatGPT`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=💬 Copilot`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🤖 AI`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🪙 加密货币`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=📹 YouTube`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🎥 Netflix`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🎥 DisneyPlus`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🎥 HBO`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🎥 PrimeVideo`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🎥 Emby`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🎻 Spotify`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=📺 Bahamut`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动
custom_proxy_group=🎶 网易音乐`select`[]DIRECT
custom_proxy_group=📺 国内媒体`select`[]DIRECT
custom_proxy_group=🌎 国外媒体`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🛒 国外电商`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🇬 谷歌服务`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🍎 苹果服务`select`[]DIRECT
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT
custom_proxy_group=🍘️ 小米服务`select`[]DIRECT
custom_proxy_group=🎮 游戏平台`select`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🎮 Steam`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🚀 测速工具`select`[]DIRECT`[]美国-自动`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]美国-自动`[]哥伦比亚-家里`[]哥伦比亚-公司`[]南美-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]欧洲-自动
custom_proxy_group=🎯 全球直连`select`[]DIRECT

custom_proxy_group=美国-自动`url-test`(广美|美|US|纽约|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|迈阿密|芝加哥|🇺🇸|United States)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=哥伦比亚-家里`url-test`(哥伦比亚)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=哥伦比亚-公司`url-test`(哥伦比亚)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=南美-自动`url-test`(秘鲁|墨西|哥伦比亚|智利|巴西|Australia|Konghwaguk)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=香港-自动`url-test`(广港|香港|HK|Hong Kong|🇭🇰|HongKong)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=台湾-自动`url-test`(广台|台湾|TW|Tai Wan|🇹🇼|🇨🇳|TaiWan|Taiwan)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=日本-自动`url-test`(广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=新加坡-自动`url-test`(广新|新加坡|SG|坡|狮城|🇸🇬|Singapore)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=韩国-自动`url-test`(广韩|韩国|KR|首尔|春川|🇰🇷|Korea)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=欧洲-自动`url-test`(克兰|比利时|尔兰|立陶宛|冰岛|耳其|利亚|埃及|希腊|斯洛伐克|芬兰|阿联|英国|德国|南非|意大|法国|加拿|罗斯|瑞士|瑞典|荷兰|沙特|班牙|Australia|Konghwaguk)`http://www.gstatic.com/generate_204`60,150
;设置分组标志位

;下方参数请勿修改
enable_rule_generator=true
overwrite_original_rules=true

